//! Half-asynchronous, half-synchronous implementation of an [Apache Thrift] server.
//! Connections are accepted and read asynchronously, while requests are
//! dispatched through the fully synchronous processors generated by the
//! [`thrift`] crate.

use std::{
    io::{self, Cursor, Read},
    path::Path,
    sync::Arc,
};
use thrift::{
    protocol::{TBinaryInputProtocol, TBinaryOutputProtocol},
    server::TProcessor,
};
use tokio::{
    io::{AsyncRead, AsyncReadExt, AsyncWrite, AsyncWriteExt},
    runtime::Runtime,
    sync::{Semaphore, watch},
};

#[cfg(unix)]
use tokio::net::UnixListener;
#[cfg(windows)]
use tokio::net::windows::named_pipe::ServerOptions;

/// A handle that can be used to stop a running [`ExtensionServer`].
///
/// Dropping the handle or calling [`stop`](StopHandle::stop) signals the
/// server's accept loop to exit. In-flight requests are aborted when the
/// server's runtime shuts down.
#[derive(Clone, Debug)]
pub struct StopHandle {
    sender: watch::Sender<bool>,
}

impl StopHandle {
    /// Signal the server to stop accepting new connections and exit.
    pub fn stop(&self) {
        let _ = self.sender.send(true);
    }
}

/// Maximum concurrently served connections. Further accepts wait until a
/// connection closes, bounding tasks, request buffers, and the extra threads
/// `block_in_place` can demote.
const MAX_CONCURRENT_CONNECTIONS: usize = 128;

pub struct ExtensionServer<PRC: TProcessor + Send + Sync + 'static> {
    processor: Arc<PRC>,
    runtime: Runtime,
    stop_rx: watch::Receiver<bool>,
    stop_tx: watch::Sender<bool>,
    connection_permits: Arc<Semaphore>,
    /// Connections currently being served; lets the dispatch path skip
    /// `block_in_place` bookkeeping when no other connection could starve.
    active_connections: Arc<std::sync::atomic::AtomicUsize>,
}

impl<PRC: TProcessor + Send + Sync + 'static> ExtensionServer<PRC> {
    /// Create a new almost-asynchronous server, from a synchronous request `TProcessor`.
    /// Input/Output protocol **must** be binary.
    pub fn new(processor: PRC) -> io::Result<ExtensionServer<PRC>> {
        Self::with_connection_limit(processor, MAX_CONCURRENT_CONNECTIONS)
    }

    fn with_connection_limit(processor: PRC, limit: usize) -> io::Result<ExtensionServer<PRC>> {
        let (stop_tx, stop_rx) = watch::channel(false);
        Ok(ExtensionServer {
            processor: Arc::new(processor),
            runtime: Runtime::new()?,
            stop_rx,
            stop_tx,
            connection_permits: Arc::new(Semaphore::new(limit)),
            active_connections: Arc::new(std::sync::atomic::AtomicUsize::new(0)),
        })
    }

    /// Returns a [`StopHandle`] that can be used to stop the server from
    /// another thread. Calling [`StopHandle::stop`] will cause the accept
    /// loop in [`listen`](ExtensionServer::listen) to exit.
    pub fn stop_handle(&self) -> StopHandle {
        StopHandle {
            sender: self.stop_tx.clone(),
        }
    }

    /// Listen for incoming connections on a `listen_path`.
    pub fn listen<P: AsRef<Path>>(&mut self, path: P) -> io::Result<()> {
        #[cfg(unix)]
        return self.listen_uds(path);
        #[cfg(windows)]
        return self.listen_pipe(path);
    }

    #[cfg(windows)]
    fn listen_pipe<P: AsRef<Path>>(&mut self, path: P) -> io::Result<()> {
        let mut stop_rx = self.stop_rx.clone();
        self.runtime.block_on(async {
            let pipe_name = path.as_ref();
            let mut server = ServerOptions::new()
                .first_pipe_instance(true)
                .create(path.as_ref())?;
            loop {
                // Wait for connection capacity before accepting so the
                // served-connection count stays bounded.
                let permit = tokio::select! {
                    permit = Arc::clone(&self.connection_permits).acquire_owned() => {
                        let Ok(permit) = permit else { break };
                        permit
                    }
                    _ = stop_rx.changed() => {
                        break;
                    }
                };
                tokio::select! {
                    result = server.connect() => {
                        match result {
                            Ok(()) => {
                                // Rotate to a fresh pipe instance before handing the connected one to a task.
                                self.handle_connection(std::mem::replace(
                                    &mut server,
                                    ServerOptions::new().create(pipe_name)?,
                                ), permit);
                            }
                            Err(e) => {
                                #[cfg(feature = "tracing")]
                                tracing::error!("failed to accept remote connection: {e:?}");
                                return Err(e);
                            }
                        }
                    }
                    _ = stop_rx.changed() => {
                        break;
                    }
                }
            }
            Ok(())
        })
    }

    #[cfg(unix)]
    fn listen_uds<P: AsRef<Path>>(&mut self, socket_path: P) -> io::Result<()> {
        let mut stop_rx = self.stop_rx.clone();
        self.runtime.block_on(async {
            let listener = UnixListener::bind(socket_path)?;
            loop {
                // Wait for connection capacity before accepting so the
                // served-connection count stays bounded.
                let permit = tokio::select! {
                    permit = Arc::clone(&self.connection_permits).acquire_owned() => {
                        let Ok(permit) = permit else { break };
                        permit
                    }
                    _ = stop_rx.changed() => {
                        break;
                    }
                };
                tokio::select! {
                    result = listener.accept() => {
                        match result {
                            Ok((stream, _)) => self.handle_connection(stream, permit),
                            Err(e) => {
                                #[cfg(feature = "tracing")]
                                tracing::error!("failed to accept remote connection: {e:?}");
                                return Err(e);
                            }
                        }
                    }
                    _ = stop_rx.changed() => {
                        break;
                    }
                }
            }
            Ok(())
        })
    }

    /// Spawn a task on the server runtime that serves Thrift requests on the
    /// given connection until the peer disconnects or a fatal error occurs.
    /// The permit is held for the connection's lifetime to enforce the cap.
    fn handle_connection<RW: AsyncRead + AsyncWrite + Send + 'static>(
        &self,
        stream: RW,
        permit: tokio::sync::OwnedSemaphorePermit,
    ) {
        let processor = Arc::clone(&self.processor);
        let active_connections = Arc::clone(&self.active_connections);
        self.runtime.spawn(async move {
            let _permit = permit;
            active_connections.fetch_add(1, std::sync::atomic::Ordering::SeqCst);
            let served = serve_connection(processor.as_ref(), stream, &active_connections).await;
            active_connections.fetch_sub(1, std::sync::atomic::Ordering::SeqCst);
            if let Err(err) = served {
                #[cfg(feature = "tracing")]
                tracing::error!("connection closed with error: {err}");
                #[cfg(not(feature = "tracing"))]
                let _ = err;
            }
        });
    }
}

/// Maximum bytes a single buffered request may occupy. Connections sending
/// larger (or never-completing) messages are closed to bound memory use.
const MAX_REQUEST_BYTES: usize = 32 * 1024 * 1024;
const READ_CHUNK_BYTES: usize = 8 * 1024;

/// Reader over buffered request bytes that records when the parser tried to
/// read past the end of the buffer, i.e. the buffered request is incomplete.
struct EofTrackingReader<'a> {
    cursor: Cursor<&'a [u8]>,
    hit_end: bool,
}

impl Read for EofTrackingReader<'_> {
    fn read(&mut self, buf: &mut [u8]) -> io::Result<usize> {
        let read = Read::read(&mut self.cursor, buf)?;
        if read == 0 && !buf.is_empty() {
            self.hit_end = true;
        }
        Ok(read)
    }
}

/// Serve Thrift requests on one connection until the peer disconnects.
///
/// Incoming bytes accumulate in a buffer because the synchronous Thrift
/// processor cannot wait for more bytes mid-message. An incomplete request
/// is detected at the transport level via [`EofTrackingReader`] (the
/// generated processor converts a mid-parse end-of-file into an error reply
/// rather than propagating it). Parsing fails before the handler runs, so
/// retrying once more bytes arrive is safe. After a request is processed,
/// exactly the bytes the parser consumed are drained, which keeps any
/// pipelined follow-up request intact.
async fn serve_connection<PRC, RW>(
    processor: &PRC,
    stream: RW,
    active_connections: &std::sync::atomic::AtomicUsize,
) -> io::Result<()>
where
    PRC: TProcessor,
    RW: AsyncRead + AsyncWrite,
{
    let (mut reader, mut writer) = tokio::io::split(stream);
    let mut requests = Vec::with_capacity(READ_CHUNK_BYTES);
    let mut response = Vec::with_capacity(READ_CHUNK_BYTES);
    let mut chunk = [0u8; READ_CHUNK_BYTES];
    loop {
        let read = reader.read(&mut chunk).await?;
        if read == 0 {
            return if requests.is_empty() {
                Ok(()) // Clean disconnect.
            } else {
                Err(io::Error::new(
                    io::ErrorKind::UnexpectedEof,
                    "peer disconnected mid-request",
                ))
            };
        }
        // `read` is bounded by `chunk.len()` per the `Read` contract.
        #[allow(clippy::indexing_slicing)]
        requests.extend_from_slice(&chunk[..read]);
        if requests.len() > MAX_REQUEST_BYTES {
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                format!("request exceeds {MAX_REQUEST_BYTES} bytes"),
            ));
        }

        while !requests.is_empty() {
            let mut request_reader = EofTrackingReader {
                cursor: Cursor::new(requests.as_slice()),
                hit_end: false,
            };
            let mut input = TBinaryInputProtocol::new(&mut request_reader, false);
            response.clear();
            let mut output = TBinaryOutputProtocol::new(&mut response, true);
            // The processor executes plugin code synchronously. When other
            // connections are active, block_in_place hands this worker's
            // queue to a fresh thread so a slow plugin call cannot starve
            // them (requires the multi-thread runtime, which
            // `ExtensionServer::new` always builds). When this is the only
            // connection there is nothing to starve, and dispatch stays on
            // the direct path: block_in_place costs ~3us per request, a
            // measured +48% on small-request round-trips.
            let others_active = active_connections.load(std::sync::atomic::Ordering::SeqCst) > 1;
            let result = if others_active {
                tokio::task::block_in_place(|| processor.process(&mut input, &mut output))
            } else {
                processor.process(&mut input, &mut output)
            };

            // Incomplete request: discard any error reply the processor
            // produced, keep the bytes, and wait for the rest to arrive.
            if request_reader.hit_end {
                break;
            }
            match result {
                Ok(()) => {
                    let consumed =
                        usize::try_from(request_reader.cursor.position()).unwrap_or(requests.len());
                    requests.drain(..consumed);
                    writer.write_all(&response).await?;
                }
                Err(err) => {
                    return Err(io::Error::new(
                        io::ErrorKind::InvalidData,
                        format!("processor error: {err}"),
                    ));
                }
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::server::mock::MockExtensionServerHandler;
    use crate::{client, osquery};
    use std::path::PathBuf;

    /// Thrift binary-protocol `ping` request frame (strict version header,
    /// method "ping", sequence number 1, empty args struct).
    const PING_FRAME: [u8; 17] = [128, 1, 0, 1, 0, 0, 0, 4, 112, 105, 110, 103, 0, 0, 0, 1, 0];

    // Use a unique socket per test case to avoid cross-test interference.
    fn init_server(name: &str) -> (PathBuf, StopHandle) {
        init_server_with(name, MockExtensionServerHandler {})
    }

    fn init_server_with<H: osquery::ExtensionSyncHandler + Send + Sync + 'static>(
        name: &str,
        handler: H,
    ) -> (PathBuf, StopHandle) {
        #[cfg(unix)]
        let socket: PathBuf = format!("/tmp/osquery_rs_sdk.server.{name}.test.em").into();
        #[cfg(windows)]
        let socket: PathBuf = format!(r"\\.\pipe\osquery_rs_sdk.server.{name}.test.em").into();

        std::fs::remove_file(&socket).ok();

        let processor = osquery::ExtensionSyncProcessor::new(handler);
        let mut server = ExtensionServer::new(processor).unwrap();
        let stop_handle = server.stop_handle();

        let socket_path = socket.clone();
        std::thread::spawn(move || {
            server.listen(socket_path).unwrap();
        });
        std::thread::sleep(std::time::Duration::from_millis(100));

        (socket, stop_handle)
    }

    #[test]
    fn client_ping() {
        let (test_socket, _stop) = init_server("client_ping_me");
        let mut client = client::ExtensionManagerClient::connect_with_path(test_socket).unwrap();
        client.ping().unwrap();
    }

    #[test]
    fn handle_connection() {
        let rt = tokio::runtime::Runtime::new().unwrap();
        let (read_chan, mut write_chan) = tokio::io::duplex(64);
        let server = ExtensionServer::new(osquery::ExtensionSyncProcessor::new(
            MockExtensionServerHandler {},
        ))
        .unwrap();
        let permit = server
            .connection_permits
            .clone()
            .try_acquire_owned()
            .unwrap();
        ExtensionServer::handle_connection(&server, read_chan, permit);
        rt.block_on(async move {
            write_chan.write_all(&PING_FRAME).await.unwrap();
        });
    }

    #[test]
    fn large_request_round_trips() {
        let (test_socket, _stop) = init_server("large_request");
        let mut client = client::ExtensionManagerClient::connect_with_path(test_socket).unwrap();

        // Larger than any single read chunk, so the server must buffer the
        // request across multiple reads before it parses.
        let payload = "x".repeat(256 * 1024);
        let request =
            osquery::ExtensionPluginRequest::from([("data".to_string(), payload.clone())]);

        let response = client.call("table", "echo", request).unwrap();
        assert_eq!(response.status.unwrap().code, Some(0));
        let rows = response.response.unwrap();
        assert_eq!(rows[0].get("data"), Some(&payload));
    }

    #[cfg(unix)]
    #[test]
    fn request_split_across_writes() {
        use std::io::{Read, Write};

        let (test_socket, _stop) = init_server("split_request");
        let mut stream = std::os::unix::net::UnixStream::connect(&test_socket).unwrap();
        stream
            .set_read_timeout(Some(std::time::Duration::from_secs(2)))
            .unwrap();

        stream.write_all(&PING_FRAME[..7]).unwrap();
        std::thread::sleep(std::time::Duration::from_millis(50));
        stream.write_all(&PING_FRAME[7..]).unwrap();

        let mut response = [0u8; 256];
        let read = stream.read(&mut response).unwrap();
        assert!(
            read > 0,
            "server should reply once the full request arrives"
        );
    }

    #[cfg(unix)]
    #[test]
    fn pipelined_requests_get_individual_responses() {
        use std::io::{Read, Write};

        let (test_socket, _stop) = init_server("pipelined_requests");
        let mut stream = std::os::unix::net::UnixStream::connect(&test_socket).unwrap();
        stream
            .set_read_timeout(Some(std::time::Duration::from_secs(2)))
            .unwrap();

        let mut frames = PING_FRAME.to_vec();
        frames.extend_from_slice(&PING_FRAME);
        stream.write_all(&frames).unwrap();

        // Each reply frame echoes the method name; expect both replies.
        let mut replies = Vec::new();
        let mut chunk = [0u8; 256];
        while count_occurrences(&replies, b"ping") < 2 {
            let read = stream.read(&mut chunk).expect("expected two ping replies");
            assert!(read > 0, "connection closed before both replies arrived");
            replies.extend_from_slice(&chunk[..read]);
        }
    }

    /// Connections beyond the cap must wait until an existing connection
    /// closes and frees a permit.
    #[cfg(unix)]
    #[test]
    fn connections_beyond_cap_wait_for_capacity() {
        use std::io::{Read as _, Write as _};
        use std::time::Duration;

        const LIMIT: usize = 4;
        let socket: PathBuf = "/tmp/osquery_rs_sdk.server.connection_cap.test.em".into();
        std::fs::remove_file(&socket).ok();
        let processor = osquery::ExtensionSyncProcessor::new(MockExtensionServerHandler {});
        let mut server = ExtensionServer::with_connection_limit(processor, LIMIT).unwrap();
        let _stop = server.stop_handle();
        let socket_path = socket.clone();
        std::thread::spawn(move || server.listen(socket_path).unwrap());
        std::thread::sleep(Duration::from_millis(100));

        // Hold every permit with idle connections; ping the last one to
        // prove they are all being serviced.
        let mut held: Vec<_> = (0..LIMIT)
            .map(|_| std::os::unix::net::UnixStream::connect(&socket).unwrap())
            .collect();
        let mut reply = [0u8; 64];
        let last = held.last_mut().unwrap();
        last.set_read_timeout(Some(Duration::from_secs(2))).unwrap();
        last.write_all(&PING_FRAME).unwrap();
        assert!(
            last.read(&mut reply).unwrap() > 0,
            "held connections should be serviced"
        );

        let mut probe = std::os::unix::net::UnixStream::connect(&socket).unwrap();
        probe
            .set_read_timeout(Some(Duration::from_millis(300)))
            .unwrap();
        probe.write_all(&PING_FRAME).unwrap();
        assert!(
            probe.read(&mut reply).is_err(),
            "connection beyond the cap must wait for capacity"
        );

        drop(held.pop());
        probe
            .set_read_timeout(Some(Duration::from_secs(2)))
            .unwrap();
        assert!(
            probe.read(&mut reply).unwrap() > 0,
            "probe should be serviced once capacity frees"
        );
    }

    #[cfg(unix)]
    fn count_occurrences(haystack: &[u8], needle: &[u8]) -> usize {
        haystack
            .windows(needle.len())
            .filter(|window| *window == needle)
            .count()
    }

    #[test]
    fn processor() {
        const NTHREADS: u32 = 10;
        let (test_socket, _stop) = init_server("processor");
        let (tx, rx) = std::sync::mpsc::channel();
        let mut children = Vec::new();

        for id in 0..NTHREADS {
            let test_socket = test_socket.clone();
            // The sender endpoint can be copied
            let thread_tx = tx.clone();
            let child = std::thread::spawn(move || {
                let mut client = client::ExtensionManagerClient::connect_with_path(test_socket)
                    .unwrap_or_else(|e| panic!("error connecting id: {id} {e}"));
                for i in 0..(NTHREADS * 100) {
                    client
                        .ping()
                        .unwrap_or_else(|_| panic!("ping failed id: {id} {i}"));
                }
                thread_tx.send(id).unwrap();
            });
            children.push(child);
        }
        for _ in 0..NTHREADS {
            rx.recv().unwrap();
        }
    }

    /// Reusable open/closed gate that parks callers until released.
    #[cfg(unix)]
    #[derive(Clone)]
    struct Gate(Arc<(std::sync::Mutex<bool>, std::sync::Condvar)>);

    #[cfg(unix)]
    impl Gate {
        fn new() -> Self {
            Gate(Arc::new((
                std::sync::Mutex::new(false),
                std::sync::Condvar::new(),
            )))
        }

        fn wait(&self) {
            let (lock, condvar) = &*self.0;
            let mut open = lock.lock().unwrap();
            while !*open {
                open = condvar.wait(open).unwrap();
            }
        }

        fn open(&self) {
            let (lock, condvar) = &*self.0;
            *lock.lock().unwrap() = true;
            condvar.notify_all();
        }
    }

    /// Handler whose `call` parks on a [`Gate`], simulating a slow plugin.
    #[cfg(unix)]
    struct GatedCallHandler {
        in_flight: Arc<std::sync::atomic::AtomicUsize>,
        gate: Gate,
    }

    #[cfg(unix)]
    impl osquery::ExtensionSyncHandler for GatedCallHandler {
        fn handle_ping(&self) -> thrift::Result<osquery::ExtensionStatus> {
            Ok(osquery::ExtensionStatus::new(0, "OK".to_string(), None))
        }

        fn handle_call(
            &self,
            _registry: String,
            _item: String,
            _request: osquery::ExtensionPluginRequest,
        ) -> thrift::Result<osquery::ExtensionResponse> {
            self.in_flight
                .fetch_add(1, std::sync::atomic::Ordering::SeqCst);
            self.gate.wait();
            Ok(osquery::ExtensionResponse::new(
                osquery::ExtensionStatus::new(0, "OK".to_string(), None),
                None,
            ))
        }

        fn handle_shutdown(&self) -> thrift::Result<()> {
            Ok(())
        }
    }

    /// Slow plugin calls must not starve other connections: with every tokio
    /// worker executing a blocking call, a ping on a fresh connection still
    /// has to be answered.
    #[cfg(unix)]
    #[test]
    fn slow_handler_calls_do_not_starve_other_connections() {
        use std::io::{Read as _, Write as _};
        use std::sync::atomic::{AtomicUsize, Ordering};
        use std::time::{Duration, Instant};

        let workers = std::thread::available_parallelism().map_or(4, usize::from);
        let in_flight = Arc::new(AtomicUsize::new(0));
        let gate = Gate::new();
        let handler = GatedCallHandler {
            in_flight: Arc::clone(&in_flight),
            gate: gate.clone(),
        };
        let (socket, _stop) = init_server_with("starvation", handler);

        // Saturate every runtime worker with a call parked in the handler.
        let mut callers = Vec::new();
        for _ in 0..workers {
            let socket = socket.clone();
            callers.push(std::thread::spawn(move || {
                let mut client = client::ExtensionManagerClient::connect_with_path(socket).unwrap();
                client
                    .call("table", "slow", osquery::ExtensionPluginRequest::new())
                    .unwrap();
            }));
        }
        let deadline = Instant::now() + Duration::from_secs(5);
        while in_flight.load(Ordering::SeqCst) < workers {
            assert!(
                Instant::now() < deadline,
                "slow calls did not reach the handler"
            );
            std::thread::sleep(Duration::from_millis(10));
        }

        let mut probe = std::os::unix::net::UnixStream::connect(&socket).unwrap();
        probe
            .set_read_timeout(Some(Duration::from_secs(2)))
            .unwrap();
        probe.write_all(&PING_FRAME).unwrap();
        let mut reply = [0u8; 64];
        let read = probe.read(&mut reply);

        // Release the parked calls before asserting so cleanup always runs.
        gate.open();
        for caller in callers {
            caller.join().unwrap();
        }

        assert!(
            read.as_ref().is_ok_and(|count| *count > 0),
            "ping starved while all workers ran slow calls: {read:?}"
        );
    }

    #[test]
    fn stop_handle_stops_server() {
        let (test_socket, stop) = init_server("stop_handle");

        // Verify the server is running
        let mut client = client::ExtensionManagerClient::connect_with_path(&test_socket).unwrap();
        client.ping().unwrap();

        // Stop the server
        stop.stop();

        // Give the server time to shut down
        std::thread::sleep(std::time::Duration::from_millis(200));

        // New connections should fail
        let result = client::ExtensionManagerClient::connect_with_path(&test_socket);
        assert!(result.is_err(), "should not connect after stop");
    }
}
